### ISSUE TITLE
Deployment on Dedicated Nodes Error Messages

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#226]
Tested on devnet

Trying to deploy on any of the nodes available on the dedicated nodes tab in the [portal](https://portal.dev.grid.tf/) without reserving a node gives an error as it is supposed to but the error is not clear or user friendly.

```
grid_network.net1: Creating...
grid_network.net1: Still creating... [10s elapsed]
grid_network.net1: Still creating... [20s elapsed]
╷
│ Error: Request cancelled
│ 
│   with grid_network.net1,
│   on main.tf line 12, in resource "grid_network" "net1":
│   12: resource "grid_network" "net1" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-grid_v0.1.27 plugin:

panic: runtime error: index out of range [22] with length 16

goroutine 66 [running]:
github.com/threefoldtech/substrate-client.(*Substrate).checkForError(0xc0002847c8, 0xc00017fd70, 0x2c, {0x45, 0x8d, 0x11, 0xfd, 0x1d, 0x26, 0xf4, ...}, ...)
        github.com/threefoldtech/substrate-client@v0.0.0-20220328075445-99d0ff259160/utils.go:237 +0x3dd
github.com/threefoldtech/substrate-client.(*Substrate).CreateNodeContract(0xc0004b9ce0, {0xf885d0, 0xc000214800}, 0x0, {0x0, 0x0, 0x0}, {0xc00048b6e0, 0x20}, 0x0)
        github.com/threefoldtech/substrate-client@v0.0.0-20220328075445-99d0ff259160/contract.go:184 +0x2c7
github.com/threefoldtech/terraform-provider-grid/internal/provider.deployConsistentDeployments({0xf7c3e8, 0xc000239320}, 0xc00049c0a0, 0xf82200, 0xc000595720, {0xf66ca0, 0xc0004b9f08}, 0xc0001aad80)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/common.go:402 +0x7eb
github.com/threefoldtech/terraform-provider-grid/internal/provider.deployDeployments({0xf7c3e8, 0xc000239320}, 0x0, 0x0, 0xf66ca0, {0xf66ca0, 0xc0004b9f08}, 0xc0001aad80, 0x1)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/common.go:334 +0x10b
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*NetworkDeployer).Deploy(0xc0003d94b8, {0xf7c3e8, 0xc000239320}, 0xd)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_network.go:638 +0xb9
github.com/threefoldtech/terraform-provider-grid/internal/provider.resourceNetworkCreate({0xf7c3e8, 0xc000239320}, 0xc0001f56c0, {0xcbd040, 0xc0001aad80})
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_network.go:681 +0x4f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00029aee0, {0xf7c378, 0xc000214b40}, 0x2, {0xcbd040, 0xc0001aad80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00029aee0, {0xf7c378, 0xc000214b40}, 0xc0005469c0, 0xc000291a80, {0xcbd040, 0xc0001aad80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002847e0, {0xf7c378, 0xc000214b40}, 0xc000299220)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000290c80, {0xf7c420, 0xc00045e720}, 0xc0005721c0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe023a0, 0xc000290c80}, {0xf7c420, 0xc00045e720}, 0xc000238300, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ac700, {0xf8b9d0, 0xc0000e8180}, 0xc0000b0360, 0xc00043bb30, 0x15c9ac0, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002ac700, {0xf8b9d0, 0xc0000e8180}, 0xc0000b0360, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-grid_v0.1.27 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

The issue was first reported [here](https://github.com/threefoldtech/grid_weblets/issues/662) but i'm moving it to the terraform repo since the only issue left is the terraform error message.

**Comment by OmarElawady** [comment]
Should be fixed in v0.1.29
