### ISSUE TITLE
The terraform-provider-grid_v1.6.1 plugin crashed!

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/terraform-provider-grid#394]
I get this error with my grid_kubernetes deplyoment.

│ Error: Request cancelled
│ 
│   with module.kubernetes.grid_network.networks["network1"],
│   on ../../modules/threefold/main.tf line 31, in resource "grid_network" "networks":
│   31: resource "grid_network" "networks" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.kubernetes.grid_kubernetes.k8s1,
│   on ../../modules/threefold/main.tf line 41, in resource "grid_kubernetes" "k8s1":
│   41: resource "grid_kubernetes" "k8s1" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-grid_v1.6.1 plugin:

panic: runtime error: index out of range [3] with length 0

goroutine 68 [running]:
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).getK8sFreeIP(0xc00001c240, {{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}}, 0x1c870?)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:992 +0x1d4
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).assignNodesIPs(0xc00001c240)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:520 +0xf7
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).GenerateVersionlessDeployments(0xc00001c240, {0x43?, 0x0?})
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:540 +0x36
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).Deploy(0xc00001c240, {0xf58f60, 0xc000556600}, {0xf5d1b8, 0xc0000b6068}, 0xc0006e1ce0?, 0x10?)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:661 +0x75
github.com/threefoldtech/terraform-provider-grid/internal/provider.resourceK8sCreate({0xf58f60, 0xc000556600}, 0xcc9060?, {0xc56600?, 0xc00013d4a0})
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:1011 +0x2d7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00023f6c0, {0xf58f98, 0xc000612240}, 0xd?, {0xc56600, 0xc00013d4a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00023f6c0, {0xf58f98, 0xc000612240}, 0xc00058e820, 0xc0000ecd80, {0xc56600, 0xc00013d4a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003f0570, {0xf58ef0?, 0xc000107100?}, 0xc0002bd180)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000327040, {0xf58f98?, 0xc000593e30?}, 0xc000636700)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdc4d00?, 0xc000327040}, {0xf58f98, 0xc000593e30}, 0xc0002ee9c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002228c0, {0xf5c478, 0xc00029e1a0}, 0xc0004f17a0, 0xc0003ef2f0, 0x14b2600, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002228c0, {0xf5c478, 0xc00029e1a0}, 0xc0004f17a0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-grid_v1.6.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

The files:
[terraform_k8s_deployment.zip](https://github.com/threefoldtech/test_feedback/files/10144270/terraform_k8s_deployment.zip)

**Comment by MarioBassem** [comment]
@fl0wm0ti0n thanks for the reporting this bug.
I came across this bug and I think there was an issue with a dependency that was updated in the latest release (v1.6.2). It should be working correctly now.
Please let us know if you are still facing this problem in v1.6.2

**Comment by fl0wm0ti0n** [comment]
unfortunately it doesnt work with 1.6.2...
same terraform files:


│ Error: Request cancelled
│ 
│   with module.kubernetes.grid_network.networks["network1"],
│   on ../../modules/threefold/main.tf line 31, in resource "grid_network" "networks":
│   31: resource "grid_network" "networks" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.kubernetes.grid_network.networks["network2"],
│   on ../../modules/threefold/main.tf line 31, in resource "grid_network" "networks":
│   31: resource "grid_network" "networks" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.kubernetes.grid_kubernetes.k8s1,
│   on ../../modules/threefold/main.tf line 50, in resource "grid_kubernetes" "k8s1":
│   50: resource "grid_kubernetes" "k8s1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs
│ may contain more details.
╵

Stack trace from the terraform-provider-grid_v1.6.2 plugin:

panic: runtime error: index out of range [3] with length 0

goroutine 26 [running]:
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).getK8sFreeIP(0xc0005bc5a0, {{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}}, 0x4fb9e0?)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:992 +0x1d4
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).assignNodesIPs(0xc0005bc5a0)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:520 +0xf7
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).GenerateVersionlessDeployments(0xc0005bc5a0, {0x43?, 0x0?})
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:540 +0x36
github.com/threefoldtech/terraform-provider-grid/internal/provider.(*K8sDeployer).Deploy(0xc0005bc5a0, {0xf5abb0, 0xc000077800}, {0xf5edf8, 0xc00000e0a0}, 0xc000500490?, 0x10?)
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:661 +0x75
github.com/threefoldtech/terraform-provider-grid/internal/provider.resourceK8sCreate({0xf5abb0, 0xc000077800}, 0xcca620?, {0xc57900?, 0xc0001cc960})
        github.com/threefoldtech/terraform-provider-grid/internal/provider/resource_k8s.go:1011 +0x2d7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002036c0, {0xf5abe8, 0xc0004d90e0}, 0xd?, {0xc57900, 0xc0001cc960})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002036c0, {0xf5abe8, 0xc0004d90e0}, 0xc0005cc5b0, 0xc000145a00, {0xc57900, 0xc0001cc960})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003c2630, {0xf5ab40?, 0xc00041ab00?}, 0xc000430500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000279040, {0xf5abe8?, 0xc0004d88d0?}, 0xc0001ce000)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdc6600?, 0xc000279040}, {0xf5abe8, 0xc0004d88d0}, 0xc000076ae0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e68c0, {0xf5e0b8, 0xc0002f2000}, 0xc0005b2000, 0xc0003c13b0, 0x14b4600, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001e68c0, {0xf5e0b8, 0xc0002f2000}, 0xc0005b2000, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-grid_v1.6.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by fl0wm0ti0n** [comment]
now i run it again and it worked?? i didn't change something

**Comment by fl0wm0ti0n** [comment]
yesterday i changed something again and it didn't work again with same errors. now today it works... so it seems a connection or performance issue?

as i changed in the module/main.tf the network part it worked... i didn't know if the provider has a bug or if I'm the problem?

from:
```
 resource "grid_network" "networks" {
   #for_each = local.networks
   for_each = { for n in local.networks : n.name => n }
     name                    = each.value.name
     nodes                   = each.value.nodes
     ip_range                = each.value.ip_range
     description             = each.value.description
     add_wg_access           = each.value.add_wg_access
 }
```

to:
```
resource "grid_network" "networks1" {

    name                    = local.networks[0].name
    nodes                   = local.networks[0].nodes
    ip_range                = local.networks[0].ip_range
    description             = local.networks[0].description
    add_wg_access           = local.networks[0].add_wg_access
}
```

**Comment by MarioBassem** [comment]
The plugin crashed while it was trying to assign an ip to the master node. It it was trying to access the ip range of the node which was empty. So, I added a check to make sure that the ip range is always not empty. But this behavior shouldn't even happen, so I took a look at the files you provided and found that you modified the module files, which is shouldn't happen also.

The k8s_with_module is an alternative for the k8s resource, not  complementary to it. You should only modify the file in the examples, not the module files.
I will open an issue to add some documentation on how to use the k8s with modules example to make it clear.

Again, thanks alot for the feedback.

**Comment by fl0wm0ti0n** [comment]
Thanks for your looking in this case

As the error happens not every time I run the apply, I wunder if there is something in the code :D

I don't understand what you mean about "k8s_with_module" and I cant edit modules? Terraform is made to completely individualize the code. so I can create my own modules. I made the whole stuff whitout changing an example. I know about the examples and I used them to learn about the tf-plugin, but what I mean, if I create my own project as I did, I can edit the modules since I've created them right? :D

but yeah some more docu would be nice ;) thanks!
